#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x30A59377A7763BE6 (slouken@libsdl.org)
#
Name     : SDL2_image
Version  : 2.0.5
Release  : 32
URL      : https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz
Source0  : https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz
Source1  : https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.5.tar.gz.sig
Summary  : Simple DirectMedia Layer - Sample Image Loading Library
Group    : Development/Tools
License  : BSD-3-Clause BSL-1.0 GPL-2.0 IJG Libpng MIT Zlib libtiff
Requires: SDL2_image-lib = %{version}-%{release}
Requires: SDL2_image-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-scons
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libwebp)
BuildRequires : pkgconfig(sdl2)
BuildRequires : sed
Patch1: CVE-2019-13616.patch

%description
This is a simple library to load images of various formats as SDL surfaces.
This library supports BMP, PPM, PCX, GIF, JPEG, PNG, and TIFF formats.

%package dev
Summary: dev components for the SDL2_image package.
Group: Development
Requires: SDL2_image-lib = %{version}-%{release}
Provides: SDL2_image-devel = %{version}-%{release}
Requires: SDL2_image = %{version}-%{release}

%description dev
dev components for the SDL2_image package.


%package lib
Summary: lib components for the SDL2_image package.
Group: Libraries
Requires: SDL2_image-license = %{version}-%{release}

%description lib
lib components for the SDL2_image package.


%package license
Summary: license components for the SDL2_image package.
Group: Default

%description license
license components for the SDL2_image package.


%prep
%setup -q -n SDL2_image-2.0.5
cd %{_builddir}/SDL2_image-2.0.5
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1647627366
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -fstack-protector-strong -fzero-call-used-regs=used -mno-vzeroupper -mprefer-vector-width=256 "
export FCFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -fstack-protector-strong -fzero-call-used-regs=used -mno-vzeroupper -mprefer-vector-width=256 "
export FFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -fstack-protector-strong -fzero-call-used-regs=used -mno-vzeroupper -mprefer-vector-width=256 "
export CXXFLAGS="$CXXFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -fstack-protector-strong -fzero-call-used-regs=used -mno-vzeroupper -mprefer-vector-width=256 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1647627366
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SDL2_image
cp %{_builddir}/SDL2_image-2.0.5/COPYING.txt %{buildroot}/usr/share/package-licenses/SDL2_image/e46696ddcdee46a0a69564af93818f7fb86486f1
cp %{_builddir}/SDL2_image-2.0.5/VisualC/external/lib/x64/LICENSE.jpeg.txt %{buildroot}/usr/share/package-licenses/SDL2_image/3ad6bae604193ca52623b7f9bfda7e1907ad068d
cp %{_builddir}/SDL2_image-2.0.5/VisualC/external/lib/x64/LICENSE.png.txt %{buildroot}/usr/share/package-licenses/SDL2_image/6c7eeb53e64ff1d2cf963009aac36b5c4e56e1f5
cp %{_builddir}/SDL2_image-2.0.5/VisualC/external/lib/x64/LICENSE.tiff.txt %{buildroot}/usr/share/package-licenses/SDL2_image/2ca80d6f23171dd0da1ee3a1db65058559369f55
cp %{_builddir}/SDL2_image-2.0.5/VisualC/external/lib/x64/LICENSE.webp.txt %{buildroot}/usr/share/package-licenses/SDL2_image/066b40e95d2608141384ecf3d5b2123423e59e16
cp %{_builddir}/SDL2_image-2.0.5/VisualC/external/lib/x64/LICENSE.zlib.txt %{buildroot}/usr/share/package-licenses/SDL2_image/cf6f537615dbfcec52703129d2e268bc57dd2afa
cp %{_builddir}/SDL2_image-2.0.5/VisualC/external/lib/x86/LICENSE.jpeg.txt %{buildroot}/usr/share/package-licenses/SDL2_image/3ad6bae604193ca52623b7f9bfda7e1907ad068d
cp %{_builddir}/SDL2_image-2.0.5/VisualC/external/lib/x86/LICENSE.png.txt %{buildroot}/usr/share/package-licenses/SDL2_image/6c7eeb53e64ff1d2cf963009aac36b5c4e56e1f5
cp %{_builddir}/SDL2_image-2.0.5/VisualC/external/lib/x86/LICENSE.tiff.txt %{buildroot}/usr/share/package-licenses/SDL2_image/2ca80d6f23171dd0da1ee3a1db65058559369f55
cp %{_builddir}/SDL2_image-2.0.5/VisualC/external/lib/x86/LICENSE.webp.txt %{buildroot}/usr/share/package-licenses/SDL2_image/066b40e95d2608141384ecf3d5b2123423e59e16
cp %{_builddir}/SDL2_image-2.0.5/VisualC/external/lib/x86/LICENSE.zlib.txt %{buildroot}/usr/share/package-licenses/SDL2_image/cf6f537615dbfcec52703129d2e268bc57dd2afa
cp %{_builddir}/SDL2_image-2.0.5/Xcode/Frameworks/webp.framework/Versions/A/Resources/LICENSE.webp.txt %{buildroot}/usr/share/package-licenses/SDL2_image/ff9a03d09711ea3f630767985780e5b279f45dd8
cp %{_builddir}/SDL2_image-2.0.5/debian/copyright %{buildroot}/usr/share/package-licenses/SDL2_image/cd823a650106a5aed889f3a243147619f21bac89
cp %{_builddir}/SDL2_image-2.0.5/external/libpng-1.6.37/LICENSE %{buildroot}/usr/share/package-licenses/SDL2_image/fc3951ba26fe1914759f605696a1d23e3b41766f
cp %{_builddir}/SDL2_image-2.0.5/external/libpng-1.6.37/contrib/gregbook/COPYING %{buildroot}/usr/share/package-licenses/SDL2_image/80b6f4fcbc19d7431482cba012e86f587828c1ba
cp %{_builddir}/SDL2_image-2.0.5/external/libpng-1.6.37/contrib/gregbook/LICENSE %{buildroot}/usr/share/package-licenses/SDL2_image/aa4b9207aaff26bc16c562d6cd766a9eed49af1e
cp %{_builddir}/SDL2_image-2.0.5/external/libpng-1.6.37/contrib/pngminus/LICENSE.txt %{buildroot}/usr/share/package-licenses/SDL2_image/29883b5b9150592328072643614229f6d320bc6e
cp %{_builddir}/SDL2_image-2.0.5/external/libwebp-1.0.2/COPYING %{buildroot}/usr/share/package-licenses/SDL2_image/59cd938fcbd6735b1ef91781280d6eb6c4b7c5d9
cp %{_builddir}/SDL2_image-2.0.5/external/tiff-4.0.9/COPYRIGHT %{buildroot}/usr/share/package-licenses/SDL2_image/a2f64f2a85f5fd34bda8eb713c3aad008adbb589
cp %{_builddir}/SDL2_image-2.0.5/external/zlib-1.2.11/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/SDL2_image/892b34f7865d90a6f949f50d95e49625a10bc7f0
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/SDL2/SDL_image.h
/usr/lib64/libSDL2_image.so
/usr/lib64/pkgconfig/SDL2_image.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSDL2_image-2.0.so.0
/usr/lib64/libSDL2_image-2.0.so.0.2.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SDL2_image/066b40e95d2608141384ecf3d5b2123423e59e16
/usr/share/package-licenses/SDL2_image/29883b5b9150592328072643614229f6d320bc6e
/usr/share/package-licenses/SDL2_image/2ca80d6f23171dd0da1ee3a1db65058559369f55
/usr/share/package-licenses/SDL2_image/3ad6bae604193ca52623b7f9bfda7e1907ad068d
/usr/share/package-licenses/SDL2_image/59cd938fcbd6735b1ef91781280d6eb6c4b7c5d9
/usr/share/package-licenses/SDL2_image/6c7eeb53e64ff1d2cf963009aac36b5c4e56e1f5
/usr/share/package-licenses/SDL2_image/80b6f4fcbc19d7431482cba012e86f587828c1ba
/usr/share/package-licenses/SDL2_image/892b34f7865d90a6f949f50d95e49625a10bc7f0
/usr/share/package-licenses/SDL2_image/a2f64f2a85f5fd34bda8eb713c3aad008adbb589
/usr/share/package-licenses/SDL2_image/aa4b9207aaff26bc16c562d6cd766a9eed49af1e
/usr/share/package-licenses/SDL2_image/cd823a650106a5aed889f3a243147619f21bac89
/usr/share/package-licenses/SDL2_image/cf6f537615dbfcec52703129d2e268bc57dd2afa
/usr/share/package-licenses/SDL2_image/e46696ddcdee46a0a69564af93818f7fb86486f1
/usr/share/package-licenses/SDL2_image/fc3951ba26fe1914759f605696a1d23e3b41766f
/usr/share/package-licenses/SDL2_image/ff9a03d09711ea3f630767985780e5b279f45dd8
