#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x30A59377A7763BE6 (slouken@libsdl.org)
#
Name     : SDL2_image
Version  : 2.0.4
Release  : 19
URL      : https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.4.zip
Source0  : https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.4.zip
Source99 : https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.4.zip.sig
Summary  : Simple DirectMedia Layer - Sample Image Loading Library
Group    : Development/Tools
License  : BSD-3-Clause BSL-1.0 GPL-2.0 IJG Libpng Zlib libtiff
Requires: SDL2_image-lib = %{version}-%{release}
Requires: SDL2_image-license = %{version}-%{release}
BuildRequires : SDL2-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-golang
BuildRequires : buildreq-scons
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libwebp)
BuildRequires : sed

%description
This is a simple library to load images of various formats as SDL surfaces.
This library supports BMP, PPM, PCX, GIF, JPEG, PNG, and TIFF formats.

%package dev
Summary: dev components for the SDL2_image package.
Group: Development
Requires: SDL2_image-lib = %{version}-%{release}
Provides: SDL2_image-devel = %{version}-%{release}

%description dev
dev components for the SDL2_image package.


%package lib
Summary: lib components for the SDL2_image package.
Group: Libraries
Requires: SDL2_image-license = %{version}-%{release}

%description lib
lib components for the SDL2_image package.


%package license
Summary: license components for the SDL2_image package.
Group: Default

%description license
license components for the SDL2_image package.


%prep
%setup -q -n SDL2_image-2.0.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541072098
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1541072098
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SDL2_image
cp COPYING.txt %{buildroot}/usr/share/package-licenses/SDL2_image/COPYING.txt
cp VisualC/external/lib/x64/LICENSE.jpeg.txt %{buildroot}/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x64_LICENSE.jpeg.txt
cp VisualC/external/lib/x64/LICENSE.png.txt %{buildroot}/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x64_LICENSE.png.txt
cp VisualC/external/lib/x64/LICENSE.tiff.txt %{buildroot}/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x64_LICENSE.tiff.txt
cp VisualC/external/lib/x64/LICENSE.webp.txt %{buildroot}/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x64_LICENSE.webp.txt
cp VisualC/external/lib/x64/LICENSE.zlib.txt %{buildroot}/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x64_LICENSE.zlib.txt
cp VisualC/external/lib/x86/LICENSE.jpeg.txt %{buildroot}/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x86_LICENSE.jpeg.txt
cp VisualC/external/lib/x86/LICENSE.png.txt %{buildroot}/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x86_LICENSE.png.txt
cp VisualC/external/lib/x86/LICENSE.tiff.txt %{buildroot}/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x86_LICENSE.tiff.txt
cp VisualC/external/lib/x86/LICENSE.webp.txt %{buildroot}/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x86_LICENSE.webp.txt
cp VisualC/external/lib/x86/LICENSE.zlib.txt %{buildroot}/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x86_LICENSE.zlib.txt
cp Xcode/Frameworks/webp.framework/Resources/LICENSE.webp.txt %{buildroot}/usr/share/package-licenses/SDL2_image/Xcode_Frameworks_webp.framework_Resources_LICENSE.webp.txt
cp Xcode/Frameworks/webp.framework/Versions/A/Resources/LICENSE.webp.txt %{buildroot}/usr/share/package-licenses/SDL2_image/Xcode_Frameworks_webp.framework_Versions_A_Resources_LICENSE.webp.txt
cp Xcode/Frameworks/webp.framework/Versions/Current/Resources/LICENSE.webp.txt %{buildroot}/usr/share/package-licenses/SDL2_image/Xcode_Frameworks_webp.framework_Versions_Current_Resources_LICENSE.webp.txt
cp debian/copyright %{buildroot}/usr/share/package-licenses/SDL2_image/debian_copyright
cp external/libpng-1.6.32/LICENSE %{buildroot}/usr/share/package-licenses/SDL2_image/external_libpng-1.6.32_LICENSE
cp external/libpng-1.6.32/contrib/gregbook/COPYING %{buildroot}/usr/share/package-licenses/SDL2_image/external_libpng-1.6.32_contrib_gregbook_COPYING
cp external/libpng-1.6.32/contrib/gregbook/LICENSE %{buildroot}/usr/share/package-licenses/SDL2_image/external_libpng-1.6.32_contrib_gregbook_LICENSE
cp external/libwebp-1.0.0/COPYING %{buildroot}/usr/share/package-licenses/SDL2_image/external_libwebp-1.0.0_COPYING
cp external/tiff-4.0.8/COPYRIGHT %{buildroot}/usr/share/package-licenses/SDL2_image/external_tiff-4.0.8_COPYRIGHT
cp external/zlib-1.2.11/contrib/dotzlib/LICENSE_1_0.txt %{buildroot}/usr/share/package-licenses/SDL2_image/external_zlib-1.2.11_contrib_dotzlib_LICENSE_1_0.txt
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/SDL2/SDL_image.h
/usr/lib64/libSDL2_image.so
/usr/lib64/pkgconfig/SDL2_image.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSDL2_image-2.0.so.0
/usr/lib64/libSDL2_image-2.0.so.0.2.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SDL2_image/COPYING.txt
/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x64_LICENSE.jpeg.txt
/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x64_LICENSE.png.txt
/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x64_LICENSE.tiff.txt
/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x64_LICENSE.webp.txt
/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x64_LICENSE.zlib.txt
/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x86_LICENSE.jpeg.txt
/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x86_LICENSE.png.txt
/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x86_LICENSE.tiff.txt
/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x86_LICENSE.webp.txt
/usr/share/package-licenses/SDL2_image/VisualC_external_lib_x86_LICENSE.zlib.txt
/usr/share/package-licenses/SDL2_image/Xcode_Frameworks_webp.framework_Resources_LICENSE.webp.txt
/usr/share/package-licenses/SDL2_image/Xcode_Frameworks_webp.framework_Versions_A_Resources_LICENSE.webp.txt
/usr/share/package-licenses/SDL2_image/Xcode_Frameworks_webp.framework_Versions_Current_Resources_LICENSE.webp.txt
/usr/share/package-licenses/SDL2_image/debian_copyright
/usr/share/package-licenses/SDL2_image/external_libpng-1.6.32_LICENSE
/usr/share/package-licenses/SDL2_image/external_libpng-1.6.32_contrib_gregbook_COPYING
/usr/share/package-licenses/SDL2_image/external_libpng-1.6.32_contrib_gregbook_LICENSE
/usr/share/package-licenses/SDL2_image/external_libwebp-1.0.0_COPYING
/usr/share/package-licenses/SDL2_image/external_tiff-4.0.8_COPYRIGHT
/usr/share/package-licenses/SDL2_image/external_zlib-1.2.11_contrib_dotzlib_LICENSE_1_0.txt
